### ISSUE TITLE
How do place main button at different location?

### ISSUE THREAD

**Issue by mayankverma** [marvelapp/FancyTabBar#3]
Hi, 

I would like to add main button to middle of view rather then bottom or basically at a different location than bottom center. I have tried creating another UIView and adding _fancytabbar to that as a subview, but it does not work. Any help is appreciated.

**Comment by pakmee** [comment]
Hi, unfortunately it only draws at the bottom right now. I'll update it if I get some time this weekend.

**Comment by mayankverma** [comment]
Tjanks jon.

Thanks and Regards
Mayank

**Comment by wilferrel** [comment]
@mayankverma I hope ^ PR is something you were looking for. Love this control and glad to contribute as much as possible. @pakmee

**Comment by mayankverma** [comment]
Thanks all for quick fix.

Thanks
Mayank
